
version: '3.3'

services:
  db-postgres:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - TZ=America/Mexico_City
      - PGTZ=America/Mexico_City
      - POSTGRES_USER=books
      - POSTGRES_DB=books
      - POSTGRES_PASSWORD=123456