CREATE SCHEMA IF NOT EXISTS user;

CREATE TABLE IF NOT EXISTS user.user (
  id_user  BIGSERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(200) NOT NULL,
  last_name VARCHAR(200) NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);